<!DOCTYPE html>
<!--
Filename: BrennanTable.php
Author: Brennan Cheatwood
Date: <?php echo date("Y-m-d"); ?>
Description: displays a 5x5 html table with PHP-generated random numbers using a 
nested loop structure.

-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Brennan's Random Number Table</title>
        <style>
            body {
                font-family: Arial, Helvetica, sans-serif;
                margin: 40px;
                background-color: #f2f2f2;
            }

            h1 {
                color: #333;
            }

            table {
                border-collapse: collapse;
                margin-top: 20px;
                background-color: #fff;
            }

            th {
                background-color: #4a90d9;
                color: white;
                padding: 10px 20px;
                border: 1px solid #ccc;

            }

            td {
                text-align: center;
                padding: 10px 20px;
                border: 1px solid #ccc;
            }

            tr:nth-child(even) {
                background-color: #e8f0fb;
            }
        </style>
    </head>
    <body>

    <h1>Random Number Table</h1>
    <p>This table was generated by using a PHP nested loop. Each cell contains a random number between 1 & 100.</p>

    <table>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
            <th>Column 3</th>
            <th>Column 4</th>
            <th>Column 5</th>
        </tr>

        <?php
            //outer loop controls the rows
            for ($row = 0; $row <5; $row++):
                ?>
        <tr>
            <?php
            //inner loop controls the columns
            for ($col = 0; $col < 5; $col++):
                ?>
                <td><?php echo rand(1, 100); ?></td>
                <?php
                    endfor; //end colum loop
                    ?>
        </tr>
        <?php
            endfor; //end row loop
            ?>

    </table>
    </body>
</html>